// International Polymarket wallet signals -> Polymarket US IOC orders.
const crypto=require('crypto'),db=require('./db'),P=require('./polymarket-us'),S=require('./settings'),M=require('./match-us');
const DEF={pct:5,minUsd:1000,maxPrice:85,slip:3,maxUse:100,thresh:78},DAY=864e5;
const J=(s,d)=>{try{return s?JSON.parse(s):d}catch(_){return d}},num=(x,d=0)=>Number.isFinite(Number(x))?Number(x):d;
const tkey=t=>crypto.createHash('sha1').update(`${t.transactionHash}|${t.asset}|${t.size}|${t.side}`).digest('base64').slice(0,14);
const orderCap=()=>Number(process.env.MAX_ORDER_USD)||Infinity,log=(s,e)=>s.logs.push({t:Date.now(),...e});
const getJSON=u=>fetch(u).then(r=>r.ok?r.json():Promise.reject(new Error(`${r.status} ${u.split('?')[0]}`)));
const runCtx=()=>{const T=new Map();let top;return{trades:a=>T.get(a)??T.set(a,getJSON(`https://data-api.polymarket.com/trades?user=${a}&limit=25&_=${Date.now()}`).catch(()=>[])).get(a),top:()=>top??=getJSON('https://data-api.polymarket.com/v1/leaderboard?timePeriod=ALL&orderBy=PNL&limit=10').then(r=>r.map(x=>x.proxyWallet)).catch(()=>[])}};
function cash(j){const a=j.balances||j.accounts||j,r=Array.isArray(a)?a[0]:a;return num(r?.buyingPower?.value,num(r?.buying_power?.value,num(r?.cash?.value,num(r?.availableCash?.value,num(r?.balance?.value,num(r?.balance))))))}
function pos(x){const tk=x.marketSlug||x.market_slug||x.marketMetadata?.slug||x.market?.slug,n=num(x.netPositionDecimal,num(x.netPosition,num(x.quantity,x.position))),cost=num(x.cost?.value,num(x.costBasis?.value,num(x.marketExposure?.value)));return tk&&n?{tk,side:n<0?'no':'yes',count:Math.abs(n),cost:Math.abs(cost),raw:x}:null}
// The retail API has returned both arrays and keyed objects for paginated
// portfolio data. Normalize before iterating so credential verification never
// fails merely because an account has an empty/object-shaped position list.
const rows=x=>Array.isArray(x)?x:(x&&typeof x==='object'?Object.values(x):[]);
async function account(c){const[b,p]=await Promise.all([P.balance(c),P.positions(c)]);if(!b.ok)throw new Error(`Polymarket US balance: ${b.json?.error?.message||b.json?.message||b.status}`);if(!p.ok)throw new Error(`Polymarket US positions: ${p.json?.error?.message||p.json?.message||p.status}`);const all=new Map();for(const x of rows(p.json.positions||p.json.data||p.json)){const v=pos(x);if(v)all.set(v.tk,v)}return{cash:cash(b.json),pos:all}}
async function open(){const row=await db.one("SELECT * FROM bot WHERE id='me'"),cfg={...DEF,...J(row.cfg,{})};return{row,cfg,creds:await S.getCreds().catch(()=>null),st:J(row.state,{}),copies:J(row.positions,[]),logs:[],orders:0,disable:false}}
function bad(s,e,r){s.st.errs=(s.st.errs||0)+1;log(s,{...e,st:'error',note:r.json?.error?.message||r.json?.message||r.json?.raw||`Polymarket US error ${r.status}`});if(s.st.errs>=3){s.disable=true;log(s,{trader:'bot',title:'Bot paused after 3 Polymarket US errors',st:'error'})}}
function reconcile(s,a){for(const cp of[...s.copies]){const p=a.pos.get(cp.tk);if(!p||p.count<=0){s.copies=s.copies.filter(x=>x.id!==cp.id);log(s,{trader:cp.trader,title:cp.title,tk:cp.tk,act:'sell',st:'closed',note:'position is no longer open on Polymarket US'})}else cp.count=Math.min(cp.count,p.count)}}
const fills=r=>(r.json.executions||[]).reduce((n,x)=>n+num(x.lastShares,num(x.order?.cumQuantity)),0);
async function buy(s,t,a,usd){const c=s.cfg,pm=Math.round(num(t.price)*100),base={trader:t.name||t.pseudonym||String(t.proxyWallet).slice(0,8),title:t.title,outcome:t.outcome,pm,usd,act:'buy'};const b=await M.resolve(t,c.thresh/100).catch(e=>({reason:`couldn't search Polymarket US (${String(e.message||e).slice(0,90)})`}));if(!b.m)return log(s,{...base,st:'skip',note:b.reason});const ask=Math.round(b.ask*100),e={...base,tk:b.m.slug,kt:b.m.question||b.m.title||b.m.slug,side:b.side,ask,score:b.score,asset:t.asset};if(ask<1||ask>99)return log(s,{...e,st:'skip',note:'matched US market has no executable price'});if(ask>c.maxPrice)return log(s,{...e,st:'skip',note:`US ask ${ask}¢ exceeds your ${c.maxPrice}¢ limit`});if(ask>pm+c.slip)return log(s,{...e,st:'skip',note:`US ask ${ask}¢ is more than ${c.slip}¢ above the signal's ${pm}¢`});if(ask<pm-20)return log(s,{...e,st:'skip',note:`US ask ${ask}¢ is too far below the signal's ${pm}¢ to trust the match`});if(s.copies.some(p=>p.tk===e.tk)||a.pos.has(e.tk))return log(s,{...e,st:'skip',note:'you already hold this US market'});const budget=Math.min(a.cash*c.pct/100,orderCap(),Math.max(0,a.cash-.01)),count=Math.floor(budget/(ask/100));if(count<1)return log(s,{...e,st:'skip',note:`${c.pct}% of $${a.cash.toFixed(2)} cannot buy one contract at ${ask}¢`});const exposure=s.copies.reduce((n,p)=>n+p.cost,0);if(exposure+count*ask/100>(a.cash+exposure)*c.maxUse/100)return log(s,{...e,st:'skip',note:`would exceed your ${c.maxUse}% copied-exposure limit`});if(s.orders++>=5)return log(s,{...e,st:'skip',note:'max 5 orders per check'});const r=await P.order(s.creds,{slug:e.tk,side:e.side,quantity:count,slippageBips:c.slip*100});if(!r.ok)return bad(s,e,r);s.st.errs=0;const filled=fills(r);if(filled<=0)return log(s,{...e,count,st:'skip',note:`IOC order for ${count} contracts did not fill`});const cost=filled*ask/100;a.cash-=cost;s.copies.push({id:crypto.randomBytes(6).toString('hex'),tk:e.tk,side:e.side,count:filled,cost,ask,asset:t.asset,trader:e.trader,title:t.title,kt:e.kt,t:Date.now()});log(s,{...e,count:filled,st:'bought',note:`${filled} contract${filled===1?'':'s'} at up to ${ask}¢ · match score ${e.score}/100`})}
async function sell(s,cp,why){const e={trader:cp.trader,title:cp.title,tk:cp.tk,side:cp.side,count:cp.count,act:'sell'},r=await P.closePosition(s.creds,cp.tk,s.cfg.slip*100);if(!r.ok)return bad(s,e,r);s.copies=s.copies.filter(x=>x.id!==cp.id);log(s,{...e,st:'sold',note:why})}
async function save(s,en){await db.q("UPDATE bot SET enabled=$1, state=$2, positions=$3, lock_until=NULL, updated=$4 WHERE id='me'",[en??(s.row.enabled&&!s.disable),JSON.stringify(s.st),JSON.stringify(s.copies),Date.now()]);for(const l of s.logs)await db.q('INSERT INTO botlog (id, ts, entry) VALUES ($1,$2,$3)',[crypto.randomBytes(8).toString('hex'),l.t,JSON.stringify(l)]);if(s.logs.length)await db.q('DELETE FROM botlog WHERE ts<$1',[Date.now()-14*DAY])}
async function run(ctx=runCtx(),gap=0){if(gap){const r=await db.one("SELECT state FROM bot WHERE id='me'");if(Date.now()-(J(r?.state,{}).last||0)<gap)return{ran:false,why:'ran recently'}}const got=await db.one("UPDATE bot SET lock_until=$1 WHERE id='me' AND enabled=true AND (lock_until IS NULL OR lock_until<$2) RETURNING id",[Date.now()+55e3,Date.now()]);if(!got)return{ran:false};const s=await open();try{if(!s.creds){s.disable=true;log(s,{trader:'bot',title:'Bot paused — connect Polymarket US first',st:'error'});await save(s);return{ran:true,error:'no key'}}if(process.env.TRADING_DISABLED){s.disable=true;log(s,{trader:'bot',title:'Bot paused — TRADING_DISABLED is set',st:'error'});await save(s);return{ran:true}}let addrs=(await db.q('SELECT wallet FROM follows')).map(x=>x.wallet);if(!addrs.length)addrs=await ctx.top();addrs=addrs.slice(0,15);const now=Math.floor(Date.now()/1000);if(!s.st.seen2){s.st.since=now-60;s.st.seen2=[]}s.st.since=Math.max(s.st.since||now-60,now-600);const seen=new Map(s.st.seen2),acc=s.st.acc||{},trades=(await Promise.all(addrs.map(a=>ctx.trades(a)))).flat().filter(t=>t&&t.timestamp>=s.st.since&&!seen.has(tkey(t))).sort((a,b)=>a.timestamp-b.timestamp);if(!trades.length&&Date.now()-(s.st.synced||0)<60e3){s.st.last=Date.now();s.st.watching=addrs.length;await save(s);return{ran:true,trades:0}}const a=await account(s.creds);reconcile(s,a);s.st.synced=Date.now();for(const t of trades){if(s.disable)break;seen.set(tkey(t),t.timestamp);if(t.side==='SELL'){for(const cp of s.copies.filter(p=>p.asset===t.asset))await sell(s,cp,`${cp.trader} sold the source market`)}else if(t.side==='BUY'){const v=acc[`${t.proxyWallet}|${t.asset}`.toLowerCase()]||={usd:0};acc[`${t.proxyWallet}|${t.asset}`.toLowerCase()]=v;v.usd+=num(t.size)*num(t.price);v.t=t.timestamp;if(!v.fired&&v.usd>=s.cfg.minUsd){v.fired=1;await buy(s,t,a,v.usd)}}}s.st.seen2=[...seen].filter(x=>x[1]>=s.st.since);s.st.acc=Object.fromEntries(Object.entries(acc).filter(([,x])=>x.t>=now-600));s.st.last=Date.now();s.st.watching=addrs.length;await save(s);return{ran:true,trades:trades.length,logs:s.logs.length}}catch(e){s.st.last=Date.now();log(s,{trader:'bot',title:'Check failed: '+String(e.message||e).slice(0,140),st:'error'});await save(s).catch(()=>{});return{ran:true,error:String(e.message||e)}}}
async function manualSell(target){const s=await open();if(!s.creds)throw new Error('Connect Polymarket US first');for(const cp of target==='all'?[...s.copies]:s.copies.filter(x=>x.tk===String(target)))await sell(s,cp,'sold by you');await save(s,s.row.enabled&&!s.disable)}
module.exports={DEF,run,manualSell,open,account,J,orderCap};
