// Owner-only Auto Trader controls. Signals are international wallets; all
// account data and order execution are Polymarket US.
const { handler, err, needOwner }=require('./_lib/util');
const db=require('./_lib/db'),E=require('./_lib/engine'),P=require('./_lib/polymarket-us'),S=require('./_lib/settings');
const clamp=(v,lo,hi,d)=>Number.isFinite(Number(v))?Math.min(hi,Math.max(lo,Number(v))):d;
const follows=()=>db.q('SELECT wallet, name FROM follows ORDER BY name');
const value=x=>Number(x?.value??x??0)||0;
async function state(){const s=await E.open(),[logs,follow]=await Promise.all([db.q('SELECT entry FROM botlog ORDER BY ts DESC LIMIT 60'),follows()]);const out={enabled:s.row.enabled,cfg:s.cfg,last:s.st.last||null,watching:s.st.watching||0,follows:follow,capServer:Number(process.env.MAX_ORDER_USD)||null,disabledServer:!!process.env.TRADING_DISABLED,keys:s.creds?{set:true,keyId:s.creds.keyId.slice(0,8)+'…',env:'prod',source:s.creds.source}:{set:false},log:logs.map(x=>E.J(x.entry,{})),account:null,positions:[],fills:[],accountError:null};if(!s.creds)return out;try{const[a,acts]=await Promise.all([E.account(s.creds),P.activities(s.creds)]);out.positions=[...a.pos.values()].map(p=>({tk:p.tk,side:p.side,count:p.count,cost:p.cost,value:null,pnl:null,fees:0,title:p.tk,sub:'',status:'open',copied:s.copies.some(x=>x.tk===p.tk)?{trader:s.copies.find(x=>x.tk===p.tk).trader}:null}));out.account={cash:a.cash,positionsValue:out.positions.reduce((n,p)=>n+p.cost,0)};out.account.total=out.account.cash+out.account.positionsValue;const activity=acts.json.activities||acts.json.data||[];if(acts.ok)out.fills=(Array.isArray(activity)?activity:Object.values(activity)).filter(x=>x.trade).map(x=>({t:Date.parse(x.trade.createTime)||Date.now(),tk:x.trade.marketSlug,action:x.trade.action||'buy',side:x.trade.outcomeSide||'',count:value(x.trade.qtyDecimal||x.trade.qty),price:value(x.trade.price),fee:0}));}catch(e){out.accountError=String(e.message||e)}return out}
module.exports=handler(async(req,body,q)=>{needOwner(req,await S.secret());const op=q.op||body.op;switch(op){case'state':return state();case'live':{const r=await db.one("SELECT enabled, live FROM bot WHERE id='me'");return{enabled:!!r?.enabled,live:E.J(r?.live,null),now:Date.now()}}case'cfg':{const c=body.cfg||{},cur=(await E.open()).cfg,D=E.DEF,cfg={pct:clamp(c.pct??cur.pct,.5,100,D.pct),minUsd:clamp(c.minUsd??cur.minUsd,0,1e7,D.minUsd),maxPrice:clamp(c.maxPrice??cur.maxPrice,1,99,D.maxPrice),slip:clamp(c.slip??cur.slip,0,20,D.slip),maxUse:clamp(c.maxUse??cur.maxUse,1,100,D.maxUse),thresh:clamp(c.thresh??cur.thresh,50,100,D.thresh)};await db.q("UPDATE bot SET cfg=$1 WHERE id='me'",[JSON.stringify(cfg)]);return{ok:true,cfg}}case'start':{const s=await E.open();if(!s.creds)throw err(400,'Connect your Polymarket US account first');if(process.env.TRADING_DISABLED)throw err(400,'Trading is disabled on the server');await E.account(s.creds);s.st={...s.st,since:Math.floor(Date.now()/1000)-30,seen2:[],errs:0};await db.q("UPDATE bot SET enabled=true, state=$1, lock_until=NULL WHERE id='me'",[JSON.stringify(s.st)]);return E.run()}case'stop':await db.q("UPDATE bot SET enabled=false WHERE id='me'");return{ok:true};case'runnow':return E.run();case'sell':await E.manualSell(body.ticker==='all'?'all':String(body.ticker||''));return{ok:true};case'clearlog':await db.q('DELETE FROM botlog');return{ok:true};case'followlist':return{follows:await follows()};case'follow':{const wallet=String(body.wallet||'').toLowerCase();if(!/^0x[0-9a-f]{40}$/.test(wallet))throw err(400,'bad wallet');await db.q('INSERT INTO follows (wallet,name) VALUES ($1,$2) ON CONFLICT (wallet) DO UPDATE SET name=$2',[wallet,String(body.name||'').slice(0,60)]);return{follows:await follows()}}case'unfollow':await db.q('DELETE FROM follows WHERE wallet=$1',[String(body.wallet||'').toLowerCase()]);return{follows:await follows()};case'follows':if(!Array.isArray(body.list))throw err(400,'list required');if((await follows()).length)return{follows:await follows()};for(const f of body.list.filter(f=>/^0x[0-9a-fA-F]{40}$/.test(f.wallet)).slice(0,100))await db.q('INSERT INTO follows (wallet,name) VALUES ($1,$2) ON CONFLICT (wallet) DO NOTHING',[f.wallet.toLowerCase(),String(f.name||'').slice(0,60)]);return{follows:await follows()};case'keys':{const keyId=String(body.keyId||'').trim(),secret=String(body.secret||'').trim();if(!/^[A-Za-z0-9_-]{8,160}$/.test(keyId)||!secret)throw err(400,'Enter a Polymarket US Key ID and Secret Key');const creds={keyId,secret};try{await E.account(creds)}catch(e){throw err(400,`Polymarket US rejected this key: ${e.message}`)}await S.saveCreds(creds);return{ok:true,cash:(await E.account(creds)).cash}}case'keysdel':await S.clearCreds();await db.q("UPDATE bot SET enabled=false WHERE id='me'");return{ok:true};default:throw err(400,'unknown op')}});
